# Mermin Peres Magic Square Game

In [1]:
from qiskit import *
import numpy as np

In [4]:
def check_result(results, col, row):
    for i in results: 
        i = np.array(list(i.split())).astype(np.int)[::-1]
        # bring array in correct i.e. from incoming y2,y1,x2,x1 -> x1,x2,y1,y2
        global a
        a = i[0:2]
        a_sum = np.sum(a)
        a3 = int(np.mod(a_sum+1,2))
        a = np.append(a,a3)
        winning_alice = np.mod(a_sum + a3, 2) == 1
        # compute x3 by x1+x2+1 mod 2 and save to array

        b = i[2:]
        b_sum = np.sum(b)
        b3 = int(np.mod(b_sum,2))
        b = np.append(b,b3)
        winning_bob = np.mod(b_sum + b3, 2) == 0   
        # compute y3 by y1+y2 mod 2 and save to array

        # compute overall winning condition -> alice at index of bob's row and vice versa
        if(winning_bob & winning_alice & (a[row-1]==b[col-1])):
            print("Victory!")    
            print("The following magic square wins the game!")
            k = np.empty((3,3,))
            k[:] = np.nan
            k[:,col-1] = a
            k[row-1,:] = b
            print(k)

        else:
            "The Game is lost!"

        print("\n")
    

In [ ]:
#The following function sets up the initial entanglement between Alice and Bob
def share_bell_state(qc,a,b,c,d): 
    qc.h(a)
    qc.h(b)
    qc.cx(a,c)
    qc.cx(b,d)
    
# The following functions represent the U(gamma) and V(gamma) controlled Cliffords.
def U(qc,gamma,a,b):
    if gamma==1:
        qc.h(a)
        qc.i(b)
    elif gamma==2:
        qc.swap(a,b)
        qc.h(a)
        qc.i(b)

    elif gamma==3:
        qc.cx(a,b)
        qc.h(a)
        qc.i(b)

def V(qc,gamma,a,b):
    if gamma==1:
        qc.h(a)
        qc.h(b)
    if gamma==2:
        qc.swap(a,b)
    elif gamma==3:
        qc.z(a)
        qc.z(b)
        qc.cz(a,b)
        qc.h(a)
        qc.h(b)

In [5]:
#We will ask the user to select the row and column on Alice and Bob's behalf.
print("Alice and Bob, select a column or row value of 1, 2, or 3") 
print("Alice choice (column):")
alpha = int(input())
print("Bob choice (row):")
beta = int(input())

#Create the quantum register and the classical register to store our final bit values
aliceQR = QuantumRegister(2)
x1CR = ClassicalRegister(1)
x2CR = ClassicalRegister(1)
bobQR = QuantumRegister(2)
y1CR = ClassicalRegister(1)
y2CR = ClassicalRegister(1)

#Create the circuit
magicsquare_circuit = QuantumCircuit(aliceQR,bobQR,x1CR,x2CR,y1CR,y2CR)

#Generate the Bell state on the circuit
share_bell_state(magicsquare_circuit,0,1,2,3)

magicsquare_circuit.barrier()
magicsquare_circuit.draw(output='mpl')
print(magicsquare_circuit)

#Draw the rest of the circuit based on Alice and Bob's selection   
if 4>alpha>0 and 4>beta>0:
    U(magicsquare_circuit,alpha,0,1) 
    V(magicsquare_circuit,beta,2,3)
    magicsquare_circuit.measure(0,0)
    magicsquare_circuit.measure(0,0)
    magicsquare_circuit.measure(1,1)
    magicsquare_circuit.measure(2,2)
    magicsquare_circuit.measure(3,3)
    
    backend = BasicAer.get_backend('qasm_simulator') # define the backend
    job = execute(magicsquare_circuit, backend, shots=100) # run the job simulation
    results = job.result().get_counts()
    check_result(results, alpha, beta)

else:
    print("please enter values of 1, 2, or 3")

Alice and Bob, select a column or row value of 1, 2, or 3
Alice choice (column):
Bob choice (row):
      ┌───┐           ░ 
q7_0: ┤ H ├──■────────░─
      ├───┤  │        ░ 
q7_1: ┤ H ├──┼────■───░─
      └───┘┌─┴─┐  │   ░ 
q8_0: ─────┤ X ├──┼───░─
           └───┘┌─┴─┐ ░ 
q8_1: ──────────┤ X ├─░─
                └───┘ ░ 
c4: 1/══════════════════
                        
c5: 1/══════════════════
                        
c6: 1/══════════════════
                        
c7: 1/══════════════════
                        
Victory!
The following is the winning magic square!
[[ 1.  1.  0.]
 [ 1. nan nan]
 [ 1. nan nan]]


Victory!
The following is the winning magic square!
[[ 1.  1.  0.]
 [ 0. nan nan]
 [ 0. nan nan]]


Victory!
The following is the winning magic square!
[[ 1.  0.  1.]
 [ 1. nan nan]
 [ 1. nan nan]]


Victory!
The following is the winning magic square!
[[ 0.  1.  1.]
 [ 1. nan nan]
 [ 0. nan nan]]


Victory!
The following is the winning magic square!
[[ 1.  0.  1.]
 [ 0. nan