# Mermin Peres Magic Square Game

In [52]:
from qiskit import *
import numpy as np
from qiskit.test.mock import *

In [63]:
def check_result(results, col, row):
    lost = 0 
    won = 0
    for i in results: 
        print("Quantum circuit solution")
        print(i+"\n")
        i = np.array(list(i.split())).astype(int)[::-1]
        # bring array in correct i.e. from incoming y2,y1,x2,x1 -> x1,x2,y1,y2
        a = i[0:2]
        a_sum = np.sum(a)
        a3 = int(np.mod(a_sum+1,2))
        a = np.append(a,a3)
        winning_alice = np.mod(a_sum + a3, 2) == 1
        # compute x3 by x1+x2+1 mod 2 and save to array

        b = i[2:]
        b_sum = np.sum(b)
        b3 = int(np.mod(b_sum,2))
        b = np.append(b,b3)
        winning_bob = np.mod(b_sum + b3, 2) == 0   
        # compute y3 by y1+y2 mod 2 and save to array

        # compute overall winning condition -> alice at index of bob's row and vice versa
        print("Alice's selection. Column:"+str(col)+"\n"+str(a.reshape(3,1))+"\n")
        print("Bob's circuit solution. Row:"+str(row)+"\n"+str(b)+"\n")
        
        if(winning_bob & winning_alice & (a[row-1]==b[col-1])):
            print("Victory!")    
            print("The following magic square wins the game!")
            k = np.empty((3,3,))
            k[:] = np.nan
            k[:,col-1] = a
            k[row-1,:] = b
            print(k)
            won += 
        else:
            print("The Game is lost!")
            lost += 
        print("------------------------------------------")  
        print("\n")
    print(lost)
    print(won)
    print("Accuracy:"+str(won/(lost+won)))

In [64]:
#The following function sets up the initial entanglement between Alice and Bob
def share_bell_state(qc,a,b,c,d): 
    qc.h(a)
    qc.h(b)
    qc.cx(a,c)
    qc.cx(b,d)
    
# The following functions represent the U(gamma) and V(gamma) controlled Cliffords.
def U(qc,gamma,a,b):
    if gamma==1:
        qc.h(a)
        qc.i(b)
    elif gamma==2:
        qc.swap(a,b)
        qc.h(a)
        qc.i(b)

    elif gamma==3:
        qc.cx(a,b)
        qc.h(a)
        qc.i(b)

def V(qc,gamma,a,b):
    if gamma==1:
        qc.h(a)
        qc.h(b)
    if gamma==2:
        qc.swap(a,b)
    elif gamma==3:
        qc.z(a)
        qc.z(b)
        qc.cz(a,b)
        qc.h(a)
        qc.h(b)

In [66]:
#We will ask the user to select the row and column on Alice and Bob's behalf.
print("Alice and Bob, select a column or row value of 1, 2, or 3") 
print("Alice choice (column):")
alpha = int(input())
print("Bob choice (row):")
beta = int(input())

#Create the quantum register and the classical register to store our final bit values
aliceQR = QuantumRegister(2)
x1CR = ClassicalRegister(1)
x2CR = ClassicalRegister(1)
bobQR = QuantumRegister(2)
y1CR = ClassicalRegister(1)
y2CR = ClassicalRegister(1)

#Create the circuit
magicsquare_circuit = QuantumCircuit(aliceQR,bobQR,x1CR,x2CR,y1CR,y2CR)

#Generate the Bell state on the circuit
share_bell_state(magicsquare_circuit,0,1,2,3)

magicsquare_circuit.barrier()
magicsquare_circuit.draw(output='mpl')
print(magicsquare_circuit)

#Draw the rest of the circuit based on Alice and Bob's selection   
if 4>alpha>0 and 4>beta>0:
    U(magicsquare_circuit,alpha,0,1) 
    V(magicsquare_circuit,beta,2,3)
    magicsquare_circuit.measure(0,0)
    magicsquare_circuit.measure(0,0)
    magicsquare_circuit.measure(1,1)
    magicsquare_circuit.measure(2,2)
    magicsquare_circuit.measure(3,3)
    
    backend = BasicAer.get_backend('qasm_simulator') # define the backend
    job = execute(magicsquare_circuit, backend, shots=8192, optimization_level=3) # run the job simulation
    results = job.result().get_counts()
    check_result(results, alpha, beta)
    print(results)

else:
    print("please enter values of 1, 2, or 3")

Alice and Bob, select a column or row value of 1, 2, or 3
Alice choice (column):
Bob choice (row):
        ┌───┐           ░ 
q387_0: ┤ H ├──■────────░─
        ├───┤  │        ░ 
q387_1: ┤ H ├──┼────■───░─
        └───┘┌─┴─┐  │   ░ 
q388_0: ─────┤ X ├──┼───░─
             └───┘┌─┴─┐ ░ 
q388_1: ──────────┤ X ├─░─
                  └───┘ ░ 
c100: 1/══════════════════
                          
c101: 1/══════════════════
                          
c102: 1/══════════════════
                          
c103: 1/══════════════════
                          
Quantum circuit solution
0 0 1 0

Alice's selection. Column:1
[[0]
 [1]
 [0]]

Bob's circuit solution. Row:1
[0 0 0]

Victory!
The following magic square wins the game!
[[ 0.  0.  0.]
 [ 1. nan nan]
 [ 0. nan nan]]
------------------------------------------


Quantum circuit solution
1 0 0 0

Alice's selection. Column:1
[[0]
 [0]
 [1]]

Bob's circuit solution. Row:1
[0 1 1]

Victory!
The following magic square wins the game!
[[ 0.  1.  1.